version: "3.9"
services:
  mongo:
    image: mongo
    container_name: freela-calc-db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB_DATABASE}
    ports:
      - ${MONGO_DB_PORT_LOCAL}:27017

    volumes:
      - dbdata:/usr/database/mongodb
      
volumes:
  dbdata:
    driver: 'local'
