version: "3.9"
services:
  mongo:
    image: mongo:latest
    container_name: freela-calc-db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_PASSWORD}
    ports:
      - ${MONGO_DB_PORT_LOCAL}:${MONGO_DB_PORT}

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express-freela-calc-db
    restart: always
    ports: 
      - ${MONGO_EXPRESS_PORT}:${MONGO_EXPRESS_PORT}
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_DB_PASSWORD}
     
